// AUTO-GENERATED by scripts/gen-api-client.cjs -- do not edit by hand.
// source: apps/api/openapi.json (0.1.0)

export interface ApiEnvelope<T = unknown> {
  data: T;
  error?: string;
}

export async function healthApiHealthGet(client: ApiClient, opts?: { signal?: AbortSignal; body?: unknown }): Promise<any> {
  return client.request(`/api/health`, opts);
}
export async function getCatalogApiContentCatalogGet(client: ApiClient, opts?: { signal?: AbortSignal; body?: unknown }): Promise<any> {
  return client.request(`/api/content/catalog`, opts);
}
export async function listWorkoutsEndpointApiContentWorkoutsGet(client: ApiClient, opts?: { signal?: AbortSignal; body?: unknown }): Promise<any> {
  return client.request(`/api/content/workouts`, opts);
}
export async function getWorkoutApiContentWorkouts_Slug_Get(client: ApiClient, slug: string, opts?: { signal?: AbortSignal; body?: unknown }): Promise<any> {
  return client.request(`/api/content/workouts/${slug}`, opts);
}
export async function getWorkoutBeatsApiContentWorkouts_Slug_BeatsGet(client: ApiClient, slug: string, opts?: { signal?: AbortSignal; body?: unknown }): Promise<any> {
  return client.request(`/api/content/workouts/${slug}/beats`, opts);
}
export async function listPlansApiContentPlansGet(client: ApiClient, opts?: { signal?: AbortSignal; body?: unknown }): Promise<any> {
  return client.request(`/api/content/plans`, opts);
}
export async function getPlanSlotsApiContentPlans_Slug_SlotsGet(client: ApiClient, slug: string, opts?: { signal?: AbortSignal; body?: unknown }): Promise<any> {
  return client.request(`/api/content/plans/${slug}/slots`, opts);
}
export async function createAccountApiAccountsPost(client: ApiClient, opts?: { signal?: AbortSignal; body?: unknown }): Promise<any> {
  return client.request(`/api/accounts`, opts);
}
export async function getAccountApiAccounts_Aid_Get(client: ApiClient, aid: string, opts?: { signal?: AbortSignal; body?: unknown }): Promise<any> {
  return client.request(`/api/accounts/${aid}`, opts);
}
export async function updatePreferencesApiAccounts_Aid_PreferencesPut(client: ApiClient, aid: string, opts?: { signal?: AbortSignal; body?: unknown }): Promise<any> {
  return client.request(`/api/accounts/${aid}/preferences`, opts);
}
export async function startSessionApiSessionsPost(client: ApiClient, opts?: { signal?: AbortSignal; body?: unknown }): Promise<any> {
  return client.request(`/api/sessions`, opts);
}
export async function getSessionApiSessions_Sid_Get(client: ApiClient, sid: string, opts?: { signal?: AbortSignal; body?: unknown }): Promise<any> {
  return client.request(`/api/sessions/${sid}`, opts);
}
export async function createRunApiRunsPost(client: ApiClient, opts?: { signal?: AbortSignal; body?: unknown }): Promise<any> {
  return client.request(`/api/runs`, opts);
}
export async function getRunApiRuns_Rid_Get(client: ApiClient, rid: string, opts?: { signal?: AbortSignal; body?: unknown }): Promise<any> {
  return client.request(`/api/runs/${rid}`, opts);
}
export async function submitFeedbackApiFeedbackPost(client: ApiClient, opts?: { signal?: AbortSignal; body?: unknown }): Promise<any> {
  return client.request(`/api/feedback`, opts);
}

export type OperationName = "healthApiHealthGet" | "getCatalogApiContentCatalogGet" | "listWorkoutsEndpointApiContentWorkoutsGet" | "getWorkoutApiContentWorkouts_Slug_Get" | "getWorkoutBeatsApiContentWorkouts_Slug_BeatsGet" | "listPlansApiContentPlansGet" | "getPlanSlotsApiContentPlans_Slug_SlotsGet" | "createAccountApiAccountsPost" | "getAccountApiAccounts_Aid_Get" | "updatePreferencesApiAccounts_Aid_PreferencesPut" | "startSessionApiSessionsPost" | "getSessionApiSessions_Sid_Get" | "createRunApiRunsPost" | "getRunApiRuns_Rid_Get" | "submitFeedbackApiFeedbackPost";

export class ApiClient {
  constructor(public readonly baseUrl: string, private readonly fetchImpl: typeof fetch = globalThis.fetch) {}

  async request(pathOrUrl: string, opts: { query?: Record<string, string>; body?: unknown; signal?: AbortSignal } = {}): Promise<any> {
    const url = new URL(this.baseUrl + pathOrUrl);
    for (const [k, v] of Object.entries(opts.query || {})) url.searchParams.set(k, String(v));
    const res = await this.fetchImpl(url, {
      method: opts.body ? "POST" : "GET",
      headers: { "content-type": "application/json" },
      body: opts.body ? JSON.stringify(opts.body) : undefined,
     signal: opts.signal,
   });
    if (!res.ok) throw new Error(`HTTP ${res.status} at ${pathOrUrl}`);
    return res.json();
   }
}

